export { siteConfig } from './site';
export { navigation } from './navigation';
export { industries } from './industries';
export { capabilities, technologies, techMarquee } from './capabilities';
export { processSteps, values } from './process';
export { faqItems } from './faq';
export { facts } from './facts';
export { getInsightBySlug, insightDate, insights, readingTime } from './insights';
export { projects, featuredProject } from './projects';
export { featuredCaseStudy } from './caseStudies';
export { testimonials } from './testimonials';
export { contactChannels, socialLinks } from './contact';
export { credentials } from './credentials';
